name: Classroom Tales
favicon: null
layout_spectrum: 0.2091342555359006
typography_spectrum: 0.48536252905614674
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8874090644530952
  lightness: 0.6941151041537523
  saturation: 0.6656497123185545
  rhythmicContrast: 0.6052843083161861
purpose: []
